---
- name: Dump current database
  mysql_db:
    state: dump
    name: "{{ old_database }}"
    target: "{{ dump_file_path }}"
  when: old_database is defined

- include_role:
    name: vendor/geerlingguy.mysql
  vars:
    mysql_databases:
      - name: "{{ database_name }}"
        encoding: latin1
        collation: latin1_spanish_ci
    mysql_users:
      - name: "{{ database_user }}"
        priv: "{{ database_name }}.*:ALL"
        password: "{{ database_password }}"

- name: Restore to the new database
  mysql_db:
    name: "{{ database_name }}"
    state: import
    target: "{{ dump_file_path }}"
  when: old_database is defined
