---
- include_role:
    name: vendor/geerlingguy.mysql
  vars:
    mysql_databases:
      - name: "{{ database_name }}"
        encoding: latin1
        collation: latin1_spanish_ci
    mysql_users:
      - name: "{{ database_user }}"
        priv: "{{ database_name }}.*:ALL"
        password: "{{ database_password }}"
      - name: "{{ database_metabase_user }}"
        priv: "{{ database_name }}.people:SELECT(id, uuid, created_at, updated_at, is_admin, locale, preferences, active_days_count, last_page_load_date, test_group_number, username, reset_password_sent_at, remember_created_at, sign_in_count, current_sign_in_at, last_sign_in_at, given_name, family_name, display_name, phone_number, description, image_updated_at)/{{ database_name }}.categories:SELECT/{{ database_name }}.comments:SELECT/{{ database_name }}.conversations:SELECT/{{ database_name }}.follower_relationships:SELECT/{{ database_name }}.listings:SELECT/{{ database_name }}.locations:SELECT/{{ database_name }}.messages:SELECT/{{ database_name }}.participations:SELECT/{{ database_name }}.shipping_addresses:SELECT/{{ database_name }}.stripe_payments:SELECT/{{ database_name }}.testimonials:SELECT/{{ database_name }}.transactions:SELECT/{{ database_name }}.transaction_processes:SELECT/{{ database_name }}.transaction_transitions:SELECT"
        password: "{{ database_metabase_password }}"
