---
- name: install Ruby depedencies
  shell: bash -lc "bundle install
    --gemfile {{ current_path }}/Gemfile
    --without development test
    --jobs 2
    --deployment
    --quiet"

- name: install JS dependencies
  shell: bash -lc "npm install"
  args:
    chdir: "{{ current_path }}"

- name: migrate database
  shell: bash -lc "bundle exec rake db:migrate"
  args:
    chdir: "{{ current_path }}"

- name: precompile assets
  shell: bash -lc "bundle exec rake assets:precompile"
  args:
    chdir: "{{ current_path }}"

- name: restart delayed job
  service:
    name: delayed_job
    state: restarted
    daemon_reload: yes

- name: reload unicorn
  service:
    name: donalo
    state: reloaded
