---
- name: install Ruby depedencies
  shell: bash -lc "bundle install
    --gemfile {{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}/Gemfile
    --without development test
    --jobs 2
    --deployment
    --quiet"
  become: yes
  become_user: "{{ app_user }}"

- name: migrate database
  shell: bash -lc "bundle exec rake db:migrate"
  args:
    chdir: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"

- name: precompile assets
  shell: bash -lc "bundle exec rake assets:precompile"
  args:
    chdir: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"

- name: restart delayed job
  service:
    name: delayed_job
    state: restarted

- name: reload unicorn
  service:
    name: donalo
    state: reloaded
