- name: install Ruby depedencies
  command: "bundle install \
    --gemfile {{ ansistrano_current_dir }}/Gemfile
    --without development test
    --jobs 2
    --deployment
    --quiet"

- name: reload unicorn
  service:
    name: donalo
    state: reloaded
