---
- name: install Ruby depedencies
  shell: bash -lc "bundle install
    --gemfile {{ current_path }}/Gemfile
    --without development test
    --jobs 2
    --deployment
    --quiet"

- name: install JS dependencies
  shell: bash -lc "npm install"
  args:
    chdir: "{{ current_path }}"

- name: migrate database
  shell: bash -lc "bundle exec rake db:migrate"
  args:
    chdir: "{{ current_path }}"

# This is mainly meant for setting up a new server, as it won't have
# a config/ENVIRONMENT.sphinx.conf file yet.
- name: Check if Sphinx is configured
  stat:
    path: "{{ current_path }}/config/{{ rails_environment }}.sphinx.conf"
  register: sphinx_config

- name: Generate the Sphinx configuration file
  shell: bash -lc "bundle exec rake ts:configure"
  args:
    chdir: "{{ current_path }}"
  when: not sphinx_config.stat.exists

- name: Process Sphinx indexes
  shell: bash -lc "bundle exec rake ts:index"
  args:
    chdir: "{{ current_path }}"
  when: not sphinx_config.stat.exists

- name: precompile assets
  shell: bash -lc "bundle exec rake assets:precompile"
  args:
    chdir: "{{ current_path }}"

- name: restart delayed job
  service:
    name: delayed_job
    state: restarted
  become: yes
  become_user: root

- name: reload unicorn
  service:
    name: donalo
    state: restarted
  become: yes
  become_user: root

- name: restart sphinx
  shell: bash -lc "bundle exec rake ts:restart"
  args:
    chdir: "{{ current_path }}"
