---
- name: Install base system packages
  apt:
    pkg:
      - build-essential
      - ca-certificates
      - git
      - apt-transport-https
      - curl
      - wget
      - libmysqlclient-dev
      - imagemagick
    state: present
    force: true
    update_cache: true
