---
- name: Install base system packages
  apt:
    name: [
      'build-essential',
      'ca-certificates',
      'git',
      'apt-transport-https',
      'curl',
      'wget',
      'libmysqlclient-dev'
    ]
    state: present
    force: true
    update_cache: true
