---
- include_role:
    name: vendor/jdauphant.nginx
  vars:
    nginx_configs:
      upstream:
        - upstream app_server { server unix:{{ unicorn_socket }} fail_timeout=0; }
    nginx_sites:
      donalo_https:
        template: donalo_https.conf.j2
        server_name: "{{ inventory_hostname }}"
      donalo_http:
        template: donalo_http.conf.j2
        server_name: "{{ inventory_hostname }}"
