---
- name: Create systemd unit for Unicorn
  template:
    src: unicorn.service.j2
    dest: /etc/systemd/system/donalo.service
    mode: 0644

- include_role:
    name: vendor/jdauphant.nginx
  vars:
    nginx_configs:
      upstream:
        - upstream app_server { server localhost:8080 fail_timeout=0; }
    nginx_remove_sites:
      - donalo_https
    nginx_sites:
      donalo_http:
        template: donalo_http.conf.j2
        server_name: "{{ inventory_hostname }}"
