---
- hosts: donalo
  become: yes
  roles:
    - role: vendor/ansistrano.deploy
      vars:
        ansistrano_deploy_to: /var/www/donalo
        ansistrano_deploy_via: git
        ansistrano_git_repo: https://github.com/coopdevs/sharetribe.git
        ansistrano_git_branch: master
        ansistrano_shared_paths:
          - log
          - public/system
          - vendor/bundle
        # yamllint disable-line rule:line-length
        ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/deploy/tasks/after_symlink.yml"
