---
- hosts: donalo
  become: yes
  become_user: "{{ app_user }}"
  vars:
    current_path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
  roles:
    - role: vendor/ansistrano.deploy
      vars:
        ansistrano_deploy_to: "{{ deploy_to }}"
        ansistrano_deploy_via: git
        ansistrano_git_repo: https://github.com/coopdevs/sharetribe.git
        ansistrano_git_branch: "{{ git_version }}"
        ansistrano_keep_releases: 5
        ansistrano_shared_paths:
          - log
          - pids
          - public/system
          - public/assets
          - vendor/bundle
          - .bundle
          - db/sphinx
          - tmp
        # yamllint disable-line rule:line-length
        ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/deploy/tasks/after_symlink.yml"
