---
- hosts: donalo
  become: yes
  roles:
    - role: vendor/ansistrano.deploy
      vars:
        ansistrano_deploy_to: /var/www/donalo
        ansistrano_deploy_via: git
        ansistrano_git_repo: https://github.com/coopdevs/sharetribe.git
        ansistrano_git_branch: master
        ansistrano_shared_paths:
          - log
          - tmp/pids
          - tmp/sockets
          - tmp/cache
          - public/system
          - vendor/bundle
