---
- hosts: donalo
  become: yes
  roles:
    - role: vendor/geerlingguy.security
      vars:
        security_autoupdate_enabled: true
    - role: webserver
      tags: webserver
    - role: common
      tags: common
