---
- hosts: donalo
  become: yes
  roles:
    - role: vendor/geerlingguy.security
      vars:
        security_autoupdate_enabled: true
    - role: common
      tags: common
    - role: webserver
      tags: webserver
    - role: background_jobs
      tags: background_jobs
    - role: database
      tags: database
    - role: cacheserver
      tags: cacheserver
    - role: searchserver
      tags: searchserver
