---
ansible_python_interpreter: /usr/bin/python3

app_user: "donalo"

# yamllint disable-line rule:line-length
ruby_version: "{{ lookup('url', 'https://raw.githubusercontent.com/coopdevs/sharetribe/master/.ruby-version') }}"

hetzner_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64656138386130303666663738316537643462653864373563313839356161333363613530366238
  3932396462643637333038336133626636316139636230370a613634666438356135376635353938
  38633965613737366262663136613032353938336361396135333266383537353030323561326435
  3562343732383737370a643462333831386261323238323466353362356462353233313936316365
  65303861326632633339633763613236653435653664323763643935313461376266653663633430
  38666530366335353261333836643765396461653431313362363932336136616161373433623433
  34636534306332303066663566353662636464643538653530326163363836386135386432373265
  62616562343465666366

deploy_to: /var/www/donalo
current_path: "{{ deploy_to }}/current"
shared_path: "{{ deploy_to }}/shared"
pids_path: "{{ shared_path }}/pids"

git_version: master

external_plan_service_in_use: true

old_blog_posts_redirects:
  - id: 287
    new_url: https://blog.donalo.org/2019/11/07/3a-conferencia-internacional-sobre-el-rol-de-las-entidades-sociales-y-solidarias-en-la-economia-circular/
  - id: 288
    new_url: https://blog.donalo.org/2019/11/14/como-funciona-la-reutilizacion-de-ordenadores/
  - id: 289
    new_url: https://blog.donalo.org/2019/11/21/donalo-org-participa-en-la-semana-europea-de-prevencion-de-residuos-2019/
  - id: 290
    new_url: https://blog.donalo.org/2019/11/26/estocolmo-elegida-smart-city-de-2019-en-smart-city-expo-world-congress/
  - id: 291
    new_url: https://blog.donalo.org/2019/12/03/el-desierto-de-atacama-en-chile-esta-amenazado-por-la-gran-demanda-de-vehiculos-electricos-y-telefonos-inteligentes/
  - id: 292
    new_url: https://blog.donalo.org/2019/12/11/cumbre-del-clima-de-madrid-lograr-cero-emisiones-en-2050/
  - id: 293
    new_url: https://blog.donalo.org/2019/12/18/oportunidades-laborales-de-economia-circular/
  - id: 294
    new_url: https://blog.donalo.org/2020/01/10/ereuse-pensamiento-circular-en-torno-a-la-reutilizacion-de-dispositivos-informaticos/
  - id: 295
    new_url: https://blog.donalo.org/2020/01/15/un-procomun-circular-para-dispositivos-electronicos/
  - id: 296
    new_url: https://blog.donalo.org/2020/01/16/tendencias-en-sustentabilidad-y-empresa-para-2020/
  - id: 297
    new_url: https://blog.donalo.org/2020/01/23/comando-circular-la-obsolescencia-programada-tiene-arreglo/
  - id: 298
    new_url: https://blog.donalo.org/2020/01/30/apple-google-y-otras-grandes-tecnologicas-acusadas-de-abusos-a-ninos-en-minas-de-cobalto/
  - id: 299
    new_url: https://blog.donalo.org/2020/02/05/nueva-herramienta-para-ayudar-a-las-empresas-a-medir-su-enfoque-en-economia-circular/
  - id: 300
    new_url: https://blog.donalo.org/2020/02/11/las-cadenas-de-valor-mundiales-aceleran-el-desarrollo-sostenible/
  - id: 301
    new_url: https://blog.donalo.org/2020/02/20/el-mobile-social-congress-de-este-ano-se-centrara-en-los-impactos-ambientales-que-genera-la-industria-electronica/
  - id: 303
    new_url: https://blog.donalo.org/2020/03/04/alternativas-de-consumo-de-las-tic-hacia-un-modelo-mas-justo-y-democratico-ganadora-del-ideaton-del-msc/
  - id: 304
    new_url: https://blog.donalo.org/2020/03/05/donde-puede-crear-valor-la-economia-circular/
  - id: 305
    new_url: https://blog.donalo.org/2020/03/13/agenda-2032-una-mirada-al-futuro-de-la-economia-sostenible/
  - id: 306
    new_url: https://blog.donalo.org/2020/03/24/la-cuarentena-por-el-coronavirus-mejora-la-calidad-del-aire-pero-no-sustituye-la-accion-climatica/
  - id: 307
    new_url: https://blog.donalo.org/2020/03/31/preguntas-sobre-coronavirus-y-cambio-climatico/
  - id: 308
    new_url: https://blog.donalo.org/2020/04/09/el-coronavirus-saca-a-la-luz-el-drama-de-la-desigualdad-tecnologica/
  - id: 310
    new_url: https://blog.donalo.org/2020/04/17/la-crisis-del-coronavirus-evidencia-la-brecha-digital-tras-la-suspension-de-las-clases/
  - id: 311
    new_url: https://blog.donalo.org/2020/04/29/alianza-para-construir-el-futuro-de-la-sostenibilidad-post-covid-19/
  - id: 312
    new_url: https://blog.donalo.org/2020/04/30/entidades-sociales-impulsan-el-proyecto-ningun-nino-sin-ordenador-para-luchar-contra-la-brecha-digital/
  - id: 313
    new_url: https://blog.donalo.org/2020/05/08/que-hacer-para-una-recuperacion-economica-verde-tras-la-crisis-por-covid-19/
  - id: 314
    new_url: https://blog.donalo.org/2020/05/15/coronavirus-y-las-oportunidades-para-un-mayor-desarrollo-del-modelo-de-economia-circular/
  - id: 315
    new_url: https://blog.donalo.org/2020/05/21/el-covid-19-promueve-una-forma-mas-sostenible-de-gestionar-la-biodiversidad-urbana/
  - id: 316
    new_url: https://blog.donalo.org/2020/05/28/la-covid-19-acelera-el-proceso-hacia-una-sociedad-sin-despilfarro/
  - id: 317
    new_url: https://blog.donalo.org/2020/06/04/el-gobierno-aprueba-la-estrategia-espanola-de-economia-circular/

old_blog_tags_redirects:
  - name: reutilizaci%C3%B3n
    new_url: https://blog.donalo.org/tag/reutilizacion/
  - name: medio%20medio%20ambiente
    new_url: https://blog.donalo.org/tag/medio-ambiente/
  - name: donar%20ordenadores
    new_url: https://blog.donalo.org/tag/donar-ordenadores/
  - name: economia%20circular
    new_url: https://blog.donalo.org/tag/economia-circular/
  - name: procom%C3%BAn
    new_url: https://blog.donalo.org/tag/procomun/
